# Generated by Django 4.1.8 on 2023-04-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_category_comment_content_school_delete_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='school',
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
