# Generated by Django 4.1.8 on 2023-04-09 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
